let cleanupExplore=()=>{};
let cleanupEntrances=()=>{};
const C = window.BEARAI;
const esc = value => String(value ?? '').replace(/[&<>"']/g, x => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const routes = [['','Home'],['about','About'],['people','People'],['events','Events'],['resources','Resources'],['connections','Connections'],['recognition','Recognition'],['projects','Projects'],['community','Community'],['join','Join BearAI']];
const link = (path,label,cls='text-link') => `<a class="${cls}" href="#/${path}">${label}</a>`;
const badge = text => `<span class="badge">${text}</span>`;
const pending = text => `<button class="disabled" disabled>${text} · Coming soon</button>`;
const intro = (label,title,text) => `<div class="page-intro"><span class="eyebrow">${label}</span><h1>${title}</h1><p>${text}</p></div>`;
const placeholder = (title,detail='Photo and caption to be added.') => `<div class="photo-placeholder"><span class="photo-icon" aria-hidden="true">▧</span><strong>${title}</strong><small>${detail}</small></div>`;
const photo = () => {const h=(C.communityHighlights||[]).find(h=>{const e=C.events.find(e=>e.id===h.eventId&&!e.hidden);return e?.photos?.[h.photoIndex||0];});if(!h)return placeholder('Picnic Palooza','Photo and event details to be added.');const e=C.events.find(e=>e.id===h.eventId),p=e.photos[h.photoIndex||0];return `<figure class="featured-photo"><img class="real-photo" src="${esc(p.src)}" alt="${esc(p.alt)}"><figcaption>${esc(p.caption)}${e.photoCredit?`<br><small>${esc(e.photoCredit)}</small>`:''} · ${link('events/'+encodeURIComponent(e.id),'Event details & gallery')}</figcaption></figure>`;};
function network(){return BearVisual.markup();}
function setupNetwork(){BearVisual.mount();}
function eventDate(e){
 if(!e.start&&e.proposedDate)return planDate(e)+' (tentative) · Time to be announced';
 if(!e.start||!Number.isFinite(Date.parse(e.start)))return 'Date & time to be announced';
 const zone=e.timeZone||'America/Chicago';
 const date=value=>new Intl.DateTimeFormat('en-US',{weekday:'long',year:'numeric',month:'long',day:'numeric',timeZone:zone}).format(new Date(value));
 const time=value=>new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:new Date(value).getUTCMinutes()===0?undefined:'2-digit',timeZone:zone}).format(new Date(value));
 const end=e.end&&Number.isFinite(Date.parse(e.end))?e.end:null;
 if(e.id==='general-interest'||e.id==='workshop-1'||e.id==='service-event-2026'){
  const startTime=time(e.start),endTime=end?time(end):null;
  const sameDay=end&&date(e.start)===date(end);
  const sharedPeriod=sameDay&&startTime.match(/(AM|PM)$/)?.[0]===endTime.match(/(AM|PM)$/)?.[0];
  return date(e.start)+' · '+(sharedPeriod?startTime.replace(/\s*(AM|PM)$/,''):startTime)+(end?'–'+(sameDay?'':date(end)+' · ')+endTime:'');
 }
 return date(e.start)+' · '+time(e.start)+(end?'–'+(date(end)!==date(e.start)?date(end)+' · ':'')+time(end):'')+' ('+zone+')';
}
function eventMedia(e,detail=false){if(!detail&&e.flyer&&e.photos?.length){const p=e.photos[e.previewPhotoIndex??e.mainPhotoIndex??0];return `<div class="past-gallery"><figure><img src="${esc(e.flyer)}" alt="${esc(e.flyerAlt||e.title+' promotional flyer')}" loading="lazy"><figcaption>Promotional flyer</figcaption></figure><figure><img src="${esc(p.src)}" alt="${esc(p.alt)}" loading="lazy"><figcaption>${esc(p.caption)}</figcaption></figure></div>`;}const p=e.photos?.[e.mainPhotoIndex];return `${p?`<figure class="event-promotion"><img class="event-flyer" src="${esc(p.src)}" alt="${esc(p.alt)}"><figcaption>${esc(p.caption)}</figcaption></figure>`:""}${e.image?`<figure class="event-promotion"><img class="event-flyer" src="${esc(e.image)}" alt="${esc(e.imageAlt||e.title+' promotional artwork')}">${e.imageCaption?`<figcaption>${esc(e.imageCaption)}</figcaption>`:''}</figure>`:''}${e.flyer&&e.mainPhotoIndex!==undefined?`<p><a class="text-link" href="${esc(e.flyer)}" target="_blank" rel="noopener">View original promotional flyer ↗</a></p>`:e.flyer?`<figure class="event-promotion"><img class="event-flyer" src="${esc(e.flyer)}" alt="${esc(e.flyerAlt||e.title+' promotional flyer')}"><figcaption>Promotional flyer</figcaption></figure>`:''}`;}
function eventGallery(e){return `<h3 class="section-sub">Event photos</h3>${e.photoCredit?`<p class="missing">${esc(e.photoCredit)}</p>`:""}${e.photos?.length?`<div class="past-gallery">${e.photos.map(p=>`<figure><img src="${esc(p.src)}" alt="${esc(p.alt)}" loading="lazy"><figcaption>${esc(p.caption)}</figcaption></figure>`).join('')}</div>`:placeholder('Event photos coming soon.','Photos will be added when available.')}`;}
function pastEventCard(e,detail=false){
 // Preserve the approved Picnic Palooza recap and two-image layout.
 if(e.id==='picnic-palooza-2026')return `<article class="card event-row" id="${esc(e.id)}"><h3>${esc(e.title)}</h3><p>${esc(new Intl.DateTimeFormat('en-US',{dateStyle:'long',timeZone:e.timeZone||'America/Chicago'}).format(new Date(e.start)))} · ${esc(e.location)}</p><div class="past-gallery">${(detail?(e.photos||[]):(e.photos||[]).slice(0,2)).map(p=>`<figure><img src="${esc(p.src)}" alt="${esc(p.alt)}" loading="lazy"><figcaption>${esc(p.caption)}</figcaption></figure>`).join('')}</div><p>${esc(e.description)}</p>${e.url?safeLink(e.url,e.urlLabel||'Event details'):''}${!detail&&hasEventDetails(e)?link('events/'+encodeURIComponent(e.id),'Event details & gallery'):''}</article>`;
 return eventCard(e,false,false,true);
}
function eventDescription(e){return esc(e.description).replace(/\n\n/g,'</p><p>').replace('Please bring a laptop.','<strong>Please bring a laptop.</strong>');}
function eventLinkLabel(e){return e.photos?.length?'Event details & gallery':'Event details';}
function eventCard(e,compact=false,detail=false,past=false){return `<article class="card event-row" id="${esc(e.id)}"><h${compact?'2':'3'}>${esc(e.title)}</h${compact?'2':'3'}>${e.status?badge(esc(e.status)):''}${eventMedia(e,detail)}<p>${eventDescription(e)}</p><p>${esc(eventDate(e))}<br>${esc(e.location||'Location to be announced')}</p>${compact?'':`${e.food?`<p>${esc(e.food)}</p>`:''}${e.details?`<p>${esc(e.details)}</p>`:''}${e.mealNote?`<p>${esc(e.mealNote)}</p>`:''}${e.virtual?`<p>${esc(e.virtual)}</p>`:''}<div class="advisor-links">${e.url?safeLink(e.url,e.urlLabel||'Official event details'):''}${e.registration?safeLink(e.registration,'Organizer’s registration page'):''}</div>${e.sponsor?`<p class="missing">Event sponsor: ${esc(e.sponsor)}</p>`:''}${past?`${e.recap?`<h3>Recap</h3><p>${esc(e.recap)}</p>`:''}${detail||!e.photos?.length?(e.photos?.length?eventGallery(e):''):e.photoCredit?`<p class="missing">${esc(e.photoCredit)}</p>`:""}`:''}`}${!detail&&hasEventDetails(e)?link('events/'+encodeURIComponent(e.id),eventLinkLabel(e)):''}</article>`;}
function hasEventDetails(e){return !e.detailsPending&&(e.status==='Confirmed'||e.photos?.length||e.details||e.recap||e.registration||e.url);}
function featuredEvent(){const e=BearEvents.next(C.events),undated=BearEvents.classify(C.events).planned;return `<div class="event-feature"><section class="section split"><div><span class="eyebrow">Up next</span><h2>${e?'Our next event.':'Upcoming events'}</h2>${e?'':`<p>No upcoming event has a confirmed date yet.${undated.length?' Details for the next gathering are being finalized.':''}</p>`}${link('events','View all events ↗')}</div>${e?eventCard(e,true):undated.length?eventCard(undated[0],true):'<div class="card"><h3>Check back soon.</h3><p>Upcoming events will appear here as they are announced.</p></div>'}</section></div>`;}

function home(){return `<section class="hero"><div class="hero-copy"><span class="eyebrow">Baylor’s artificial intelligence club</span><h1 class="entrance"><span>Learn AI.</span><span>Build with AI.</span><em>Connect with AI.</em></h1><p>Learn how AI works, build projects around your interests, and meet people who want to learn alongside you.</p><div class="actions">${link('join','Join BearAI <span aria-hidden="true">↗</span>','button')}${link('about','Get to know us <span aria-hidden="true">↗</span>')}</div><p class="welcome-note">All majors. All experience levels. Your curiosity is enough.</p></div>${network()}</section>
${C.sections.activities?`<section class="section"><div class="section-heading"><div><span class="eyebrow">Room to explore</span><h2>Find your starting point.</h2></div><p>You don’t need to have it all figured out.<br>Start with a question.</p></div><div class="cards"><article class="card explore-card explore-learn"><span class="number">01 / LEARN</span><h3>Make sense of AI.</h3><p>New to AI? Start with the ideas, ask questions, and explore at your own pace.</p>${link('resources','Learning resources ↗')}</article><article class="card explore-card explore-build"><span class="number">02 / BUILD</span><h3>Turn curiosity into practice.</h3><p>Explore the project showcase as BearAI’s next chapter takes shape.</p>${link('projects','Explore projects ↗')}</article><article class="card explore-card explore-connect"><span class="number">03 / CONNECT</span><h3>Meet a different perspective.</h3><p>Find a community of students across majors, brought together by an interest in AI.</p>${link('community','Meet the community ↗')}</article></div></section>`:''}
${C.sections.featuredEvent?featuredEvent():''}
<section class="section closing-section"><div class="callout"><div><h2>Come as you are.<br>See what you can become.</h2><p>Your major doesn’t define your place in AI.</p><p class="closing-support">Start with a beginner guide, bring a question to a meeting, or share an idea for a project.</p>${link('resources','Explore beginner resources ↗')}</div></div></section>`;}
function about(){return intro('About BearAI','AI belongs to everyone.','BearAI is Baylor’s student organization for artificial intelligence, machine learning, and emerging AI technologies.')+`<section class="section"><div class="split"><div><span class="eyebrow">Our mission</span><h2>Learn together.<br>Think across disciplines.</h2><p>We bring students together to explore AI with curiosity, openness, and a willingness to learn. Every major and every experience level belongs here.</p></div><div class="card"><h3>Built around what you want to learn.</h3><p>Member interests help shape the workshops we plan and the projects we explore.</p><p>Dr. Zhao and the officers work together to turn those interests into opportunities to learn. With his guidance and the team’s coordination, we aim to help students build useful skills and experience and explore where AI fits into their studies and career goals.</p>${link('people','Meet the people ↗')}</div></div><div class="section-sub constitution-section"><h2>How BearAI is organized</h2><p>BearAI’s constitution sets out a welcoming environment for AI education, discussion, and participation across the Baylor community. Its goals connect theoretical understanding with practical technical skills, ethical AI use, and wider participation in AI.</p><div class="cards about-goals"><article class="card"><h3>Understand and participate.</h3><p>Explore AI ideas through discussion and develop the knowledge and practical skills to take part.</p></article><article class="card"><h3>Use AI thoughtfully.</h3><p>Ethical use and a diverse, welcoming AI community are central to BearAI’s goals.</p></article><article class="card"><h3>A place to get involved.</h3><p>Eligible registered Baylor students can join without prior technical experience. Dues are not required for membership or active status.</p></article></div><p>Want to learn more about how BearAI works? Take a look at our constitution.</p><a class="text-link" href="${esc(C.constitution)}" target="_blank" rel="noopener">View BearAI constitution (PDF)</a></div>${C.sections.history?`<div class="section-sub"><span class="eyebrow">Our story</span><h2>The story so far.</h2><div class="card">${badge('History to be completed')}<p>Founding details, previous milestones, and the club’s earlier chapters will appear here after they have been verified.</p></div></div>`:''}</section>`;}
function officerCard(o,advisor=false){return `<article class="card">${o.photo?`<div class="portrait-frame ${o.graduated?'small-original':''}"><img class="avatar officer-photo ${o.graduated?'small-original':''}" style="object-position:${esc(o.position||'50% 30%')};transform:scale(${o.scale||1});transform-origin:${esc(o.position||'50% 30%')}" src="${esc(o.photo)}" alt="Portrait of ${esc(o.name)}" loading="lazy"></div>`:`<div class="avatar" aria-label="Portrait placeholder">${esc(o.name?.[0]||'—')}</div>`}<p class="role">${o.graduated?'Former ':''}${esc(o.role)}</p><h3>${esc(o.name||'Appointment pending')}</h3>${advisor?`${o.bio?`<p>${esc(o.bio)}</p>`:''}<div class="advisor-links">${o.facultyProfile?safeLink(o.facultyProfile,'Baylor faculty profile'):''}${safeLink(o.website,'Personal website')}</div>`:`<dl class="officer-facts"><div><dt>Major / program</dt><dd>${esc(o.major||'To be added')}</dd></div><div><dt>${o.graduated?'Graduated':'Expected graduation'}</dt><dd>${esc(o.graduated||o.graduationYear||'To be added')}</dd></div></dl>${!o.name?'<p class="missing">Secretary appointment not yet confirmed.</p>':!o.photo?'<p class="missing">Photo to be added.</p>':''}`}${o.interests?`<p>${esc(o.interests)}</p>`:''}</article>`;}
function people(){return intro('People','A shared curiosity.<br>A student-led community.','Meet the current leadership and faculty advisor helping shape BearAI’s next chapter.')+`<section class="section"><div class="cards people">${C.officers.map(o=>officerCard(o)).join('')}${officerCard(C.advisor,true)}</div>${C.formerAdvisors?.length?`<div class="section-sub"><h2>Former faculty advisors</h2><div class="cards people">${C.formerAdvisors.map(o=>officerCard(o,true)).join('')}</div></div>`:''}${C.sections.pastOfficers?`<div class="section-sub"><h2>Past officers</h2>${C.pastOfficers.length?`<div class="cards people">${C.pastOfficers.map(o=>officerCard(o)).join('')}</div>`:`<div class="card">${badge('Records to be confirmed')}<p>Previous officers and their terms of service will be listed once verified.</p></div>`}</div>`:''}</section>`;}

function planDate(e){const value=e.start||e.proposedDate;if(!value)return 'Date unknown';return new Intl.DateTimeFormat('en-US',{month:'long',day:'numeric',timeZone:e.start?(e.timeZone||'America/Chicago'):'UTC'}).format(new Date(value));}
function semesterPlan(groups){const records=C.events.filter(e=>!e.hidden&&!e.cancelled&&(e.semester==='Fall 2026'||groups.planned.includes(e)));records.sort((a,b)=>(a.planOrder??99)-(b.planOrder??99));return '<div class="section-sub semester-plan"><h2>Fall 2026</h2><p>Our semester plans are subject to change based on event approvals, speaker availability, room reservations, and coordination with collaborating organizations. Confirmed events appear in Upcoming Events above.</p><table class="semester-table"><thead><tr><th scope="col">Date</th><th scope="col">Event</th><th scope="col">Status</th></tr></thead><tbody>'+records.map(e=>'<tr><td data-label="Date">'+esc(planDate(e))+'</td><td data-label="Event"><strong>'+esc(e.title)+'</strong>'+((e.flyer||e.image)&&e.status!=='Confirmed'?eventMedia(e):'')+(hasEventDetails(e)?'<p>'+link('events/'+encodeURIComponent(e.id),eventLinkLabel(e))+'</p>':'')+'</td><td data-label="Status">'+badge(e.status==='Confirmed'?'Confirmed':'Tentative')+'</td></tr>').join('')+'</tbody></table><p>The three AI workshops are intended to form BearAI’s main technical progression this semester.</p></div>';}
function events(){const groups=BearEvents.classify(C.events),upcoming=[...groups.ongoing,...groups.upcoming];return intro('Events','BearAI events','Upcoming gatherings, workshops, and general meetings. Explore the details below as the semester takes shape.')+`<section class="section"><h2>Upcoming Events</h2><div class="event-list">${upcoming.length?upcoming.map(e=>eventCard(e)).join(''):'<div class="card"><p>No upcoming events have a confirmed date yet. Check back for the semester’s announcements.</p></div>'}</div>${semesterPlan(groups)}${C.sections.pastEvents?`<div class="section-sub"><h2>Past Events</h2>${groups.past.length?groups.past.map(e=>pastEventCard(e)).join(''):`<div class="card">${badge('Archive to be completed')}<p>Verified event descriptions, dates, and photos will be added here.</p></div>`}</div>`:''}</section>`;}

function resources(){return intro('Resources','Start learning AI.','New to Python, machine learning, or AI? There’s room to start at your own pace, with no prior experience required.')+`<div class="section resource-sections">${window.BEAR_RESOURCES.map(category=>`<section class="resource-category"><h2>${esc(category.title)}</h2><p class="category-description">${esc(category.description)}</p><div class="resource-courses">${category.courses.map(course=>`<article class="card resource-course"><h3><a href="${esc(course.url)}" target="_blank" rel="noopener noreferrer">${esc(course.title)}</a></h3>${course.paragraphs.map(p=>`<p>${p.italic?`<em>${esc(p.text)}</em>`:esc(p.text)}</p>`).join('')}</article>`).join('')}</div></section>`).join('')}</div>`;}
function connectionEntry(e){return `<article class="card connection-entry"><div class="organization-logo ${e.logoDark?'logo-dark':' '}">${e.logo?`<img src="${esc(e.logo)}" alt="${esc(e.affiliation)} logo">`:esc(e.affiliation)}</div><div><h3>${esc(e.name)}</h3>${e.bearRole?`<span class="badge">${esc(e.bearRole)}</span>`:""}<p>${esc(e.relationship)}</p>${e.website?safeLink(e.website,"Visit website ↗"):""}</div></article>`;}
function connections(){const entries=C.connections.filter(e=>e.verified);const categories=[['Guest Speakers','Guest speaker','Confirmed guests, their affiliation, and what they shared with BearAI.'],['Collaborations','Collaboration','Verified relationships and the specific work or activity connecting them to BearAI.'],['Where They Are Now','Alumni destination','Former officers and advisors, and where their paths have taken them.']];return intro('Connections','People connected<br>with BearAI.','Guest speakers, collaborations, professional connections, and the paths of former officers and advisors.')+`<section class="section">${C.sections.connections?`<div class="connection-categories">${categories.map(([title,type,description])=>`<section class="connection-category"><h2>${title}</h2>${description?`<p>${description}</p>`:''}${type==='Alumni destination'?'<p class="missing connection-source">Details checked on LinkedIn by BearAI leadership. Last updated September 15, 2026. Dr. Rivas’s information was verified on <a href="https://www.rivas.ai/" target="_blank" rel="noopener noreferrer">his website</a>.</p>':''}<div class="connections-list">${entries.filter(e=>e.type===type||(type==='Alumni destination'&&e.type==='Former advisor destination')).map(connectionEntry).join('')||`<div class="card">${badge('Details to be verified')}<p>Entries will be added here as details are confirmed.</p></div>`}</div></section>`).join('')}</div><p class="missing">An individual’s employer or school does not imply sponsorship or partnership with BearAI.</p>`:''}</section>`;}
function recognition(){return intro('Awards & recognition','Recognizing achievement.','Celebrating the achievements of our members and the BearAI community.')+`<section class="section achievement-list">${C.recognition.filter(r=>r.verified).map(r=>`<article class="card achievement"><img class="real-photo" src="${esc(r.photo)}" alt="BearAI Team #3 at the 2025 AI Venture Challenge award presentation"><div><span class="eyebrow">${esc(r.year)} · ${esc(r.recipient)}</span><h2>${esc(r.title)}</h2><p>${esc(r.description)}</p>${safeLink(r.url,'About the competition')}</div></article>`).join('')}</section>`;}
function projects(){return intro('Projects','From “what if”<br>to what’s possible.','Explore BearAI’s hands-on projects and workshop materials.')+`<section class="section">${C.sections.projects?`<div class="cards project-list">${C.projects.map(p=>`<article class="card">${p.status?badge(esc(p.status)):''}<h2>${esc(p.title)}</h2><p>${esc(p.description)}</p>${p.topics?`<p class="project-topics"><strong>Topics:</strong> ${p.topics.map(esc).join(' · ')}</p>`:''}${p.id==='ai-study-assistant'?link('projects/'+p.id,'View Project →','button'):safeLink(p.github,'View on GitHub ↗')}</article>`).join('')}</div>`:''}<div class="quiet"><p>New to building with AI? You’re welcome here, even if you’ve never written a line of code.</p>${link('join','Start with the community ↗')}</div></section>`;}
function studyAssistant(){
 const project=C.projects.find(p=>p.id==='ai-study-assistant');
 const base='projects/ai-study-assistant';
 return intro('Project',esc(project.title),'Build a personalized AI study assistant across three hands-on BearAI workshops.')+`
 <div class="section study-project">
  <div class="study-introduction">
   ${link('projects','← All projects','text-link event-return')}
   <p>Start by designing how your assistant should behave, turn those instructions into a Python application, and then introduce retrieval so it can work with larger collections of notes and documents.</p>
   <p>Each participant builds and modifies their own assistant.</p>
   <div class="actions">${link(base+'?section=workshop-1-materials','Workshop 1 Materials','button')}${link('events','View Upcoming Events')}</div>
  </div>
  <section class="study-section" aria-labelledby="study-progression">
   <h2 id="study-progression">The Three-Part Progression</h2>
   <p class="study-flow">Design → Code → Improve</p>
   <div class="cards">
    <article class="card"><span class="number">01 / DESIGN</span><h3>Prompting and Evaluation</h3><p>Define how your assistant explains concepts, creates quizzes and flashcards, uses course notes, and responds when information is missing. No programming is required for this first workshop.</p></article>
    <article class="card"><span class="number">02 / CODE</span><h3>Python and an AI API</h3><p>Turn the behaviors explored in Workshop 1 into a small Python application that communicates with an AI model.</p></article>
    <article class="card"><span class="number">03 / IMPROVE</span><h3>Retrieval and RAG</h3><p>Introduce retrieval-augmented generation: finding relevant information in a collection of documents and supplying it to the model before it responds.</p></article>
   </div>
  </section>
  <section class="study-section" aria-labelledby="study-workshop-1">
   <span class="eyebrow">Workshop 1</span><h2 id="study-workshop-1">Design a Prompt-Based Study Assistant</h2>
   <p>Participants will use a standard AI chatbot to design and test a study assistant. They will define its goals, provide relevant context, establish rules, evaluate its responses, and revise their instructions.</p>
   <p>By the end, participants should be able to:</p>
   <ul class="study-list"><li>Explain what a prompt is.</li><li>Identify useful goals, context, rules, and output requirements.</li><li>Recognize unsupported information and instruction-following failures.</li><li>Evaluate responses for accuracy and usefulness.</li><li>Improve a prompt through repeated testing.</li></ul>
  </section>
  <section class="study-section study-materials" aria-labelledby="workshop-1-materials">
   <h2 id="workshop-1-materials" tabindex="-1">Workshop 1 Materials</h2>
   ${project.materials.map(m=>`<article class="card material-card"><div><h3>${esc(m.title)}</h3><p>${esc(m.description)}</p></div><a class="button" href="${esc(m.file)}" target="_blank" rel="noopener">${esc(m.label)} <span class="material-format">PDF ↗</span></a></article>`).join('')}
   <details class="study-explanation"><summary>Why Are the Notes Fictional?</summary><p>The Virelia Star System was created specifically for this workshop. Its details must come from the supplied notes, making it easier to test whether an assistant uses those notes correctly or introduces unsupported information.</p></details>
  </section>
  <div class="study-section study-practice">
   <section aria-labelledby="study-activities"><h2 id="study-activities">What Participants Will Do</h2>
    <ol class="study-list"><li><strong>Design:</strong> Decide how the assistant should behave.</li><li><strong>Test:</strong> Try the shared workshop questions.</li><li><strong>Challenge:</strong> Ask questions the notes cannot answer.</li><li><strong>Evaluate:</strong> Check accuracy, use of the notes, instruction-following, and usefulness.</li><li><strong>Improve:</strong> Revise the prompt and test again.</li></ol>
    <p class="study-flow">Version 1 → Test → Evaluate → Version 2</p>
   </section>
   <section aria-labelledby="study-framework"><h2 id="study-framework">A Simple Prompting Framework</h2>
    <table class="study-framework"><thead><tr><th scope="col">Element</th><th scope="col">Question</th></tr></thead><tbody>${[['Goal','What do you want the AI to do?'],['Context','What information does it need?'],['Rules','What should it do or avoid doing?'],['Output','What should the response look like?']].map(([element,question])=>`<tr><th scope="row">${element}</th><td>${question}</td></tr>`).join('')}</tbody></table>
    <p>Prompting is iterative: <strong>Define → Test → Evaluate → Improve.</strong></p>
   </section>
  </div>
  <section class="study-section study-takeaway" aria-labelledby="study-takeaway"><h2 id="study-takeaway">Workshop 1 Takeaway</h2><p>Participants should leave with reusable instructions describing how their assistant uses notes, explains material, quizzes them, provides feedback, and handles missing information.</p><p><strong>Save your prompt—you’ll build on these ideas in Workshop 2.</strong></p></section>
  <section class="study-section" aria-labelledby="study-next"><h2 id="study-next">Workshops 2 and 3</h2><div class="study-next cards">
   <article class="card"><h3>Workshop 2 — Code the Study Assistant</h3><p>Coming soon. Move from interacting directly with a chatbot to building a small Python application that communicates with an AI model.</p></article>
   <article class="card"><h3>Workshop 3 — Add Retrieval</h3><p>Coming soon. Extend the application to retrieve relevant information from larger collections of notes before generating a response.</p></article>
  </div></section>
  <div class="quiet"><div class="actions">${link('events','View Upcoming Events')}${safeLink(C.join.groupme,'Join GroupMe ↗')}</div><p class="study-signoff">Learn AI · Build with AI · Connect through AI</p></div>
 </div>`;
}

function community(){const highlights=(C.communityHighlights||[]).map(h=>({event:C.events.find(e=>e.id===h.eventId&&!e.hidden),index:h.photoIndex||0})).filter(h=>h.event?.photos?.[h.index]);return intro('Community','Life at BearAI.','Meet the students, see what we’ve been doing, and explore highlights from club activities.')+`<section class="section">${C.sections.gallery?`<div class="split">${photo()}<div><span class="eyebrow">Community highlights</span><h2>Learning together,<br>beyond the screen.</h2><p>A selection of moments from BearAI activities. Each event keeps its full photo gallery, captions, and recap on the Events page.</p>${highlights.length?'':badge('Picnic Palooza photo and event details to be added')}</div></div><div class="cards section-sub">${highlights.slice(1).map(({event,index})=>{const p=event.photos[index];return `<article class="card"><img class="real-photo" src="${esc(p.src)}" alt="${esc(p.alt)}"><h3>${esc(event.title)}</h3><p>${esc(p.caption)}</p>${event.photoCredit?`<p class="missing">${esc(event.photoCredit)}</p>`:''}${link('events/'+encodeURIComponent(event.id),'View event recap & gallery ↗')}</article>`;}).join('')}</div>`:''}</section>`;}
function eventDetail(id){const event=C.events.find(e=>e.id===id&&!e.hidden&&!e.cancelled);if(!event)return intro('Event unavailable','Event not found.','Use Events to explore the available gatherings.');const past=BearEvents.classify([event]).past.length>0;if(event.id==='picnic-palooza-2026')return intro('Past event',esc(event.title),'A moment from BearAI’s community.')+`<section class="section">${link('events','← All events','text-link event-return')}${pastEventCard(event,true)}</section>`;return intro(past?'Past event':'Event details',esc(event.title),eventDescription(event))+`<section class="section">${link('events','← All events','text-link event-return')}<div class="section-sub">${eventCard(event,false,true,past)}</div></section>`;}
function safeLink(url,label){return /^https:\/\//.test(url||'')?`<a class="text-link" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${label}</a>`:pending(label);}
function join(){return intro('Join BearAI','Bring your curiosity.<br>You belong here.','All majors. Every experience level. You don’t need a technical background to start exploring AI with us.')+`<section class="section"><div class="cards join-grid">${[['00','Baylor Connect','Please request to join BearAI on Baylor Connect. We’ll accept your request as soon as possible. Joining helps us maintain BearAI’s official membership roster through Baylor.','connect','Open Baylor Connect'],['01','GroupMe','Our main channel for club-wide communication and announcements.','groupme','Join the GroupMe'],['02','Instagram','Follow along with BearAI’s public updates.','instagram','Visit Instagram'],['03','Interest survey','Share what interests you and what you’d like to learn. Your feedback helps shape BearAI. Please take a moment to complete the survey—it’s especially important because your responses help us plan workshops, projects, and events around what you want to learn.','survey','Open interest survey'],['04','Contact us','Have a question? Get in touch with BearAI.','email','Email BearAI']].map(([n,title,desc,key,label])=>`<article class="card ${key==='connect'?'connect-card':''}"><span class="number">${n} / GET CONNECTED</span><h3>${title}</h3><p>${desc}</p>${key==='email'&&C.join.email?`<a class="text-link" href="mailto:${esc(C.join.email)}">${esc(C.join.email)}</a>`:safeLink(C.join[key],label)}</article>`).join('')}</div></section>`;}
const pages={'projects/ai-study-assistant':studyAssistant,'':home,about,people,events,resources,connections,recognition,projects,community,join};
function render(focus=false){
  const route=location.hash.replace(/^#\/?/,'').split('?')[0];
  document.querySelector('#nav').innerHTML=routes.map(([path,label])=>`<a href="#/${path}" ${(route===path||(['events','projects'].includes(path)&&route.startsWith(path+'/')))?'aria-current="page"':''} class="${path==='join'?'join-nav':''}">${label}</a>`).join('');
  document.querySelector('#main').innerHTML=route.startsWith('events/')?eventDetail(decodeURIComponent(route.slice(7))):pages[route]?pages[route]():intro('Page not found','Let’s reconnect.','This page doesn’t exist. Use the navigation to return to BearAI.');
  document.title=`${routes.find(r=>r[0]===route)?.[1]||(route==='projects/ai-study-assistant'?'AI Study Assistant':route.startsWith('events/')?'Event gallery':'Page not found')} — BearAI`;
  document.querySelector('#nav').classList.remove('open');document.querySelector('.menu').setAttribute('aria-expanded','false');
  setupNetwork();
  BearVisual.scrambleHeadings();
  mountExplore();
  mountEntrances();
  if(focus){document.querySelector('#main').focus();window.scrollTo(0,0);}
  // Hash-router query keeps the materials URL stable on GitHub Pages and refresh.
  const section=new URLSearchParams(location.hash.split('?')[1]||'').get('section');
  if(route==='projects/ai-study-assistant'&&section==='workshop-1-materials')requestAnimationFrame(()=>{
    const target=document.getElementById('workshop-1-materials');
    if(target){target.focus({preventScroll:true});target.scrollIntoView({block:'start',behavior:'instant'});}
  });
}
document.querySelector('.menu').addEventListener('click',()=>{const open=document.querySelector('#nav').classList.toggle('open');document.querySelector('.menu').setAttribute('aria-expanded',String(open));});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.querySelector('#nav').classList.contains('open')){document.querySelector('#nav').classList.remove('open');document.querySelector('.menu').setAttribute('aria-expanded','false');document.querySelector('.menu').focus();}});
window.addEventListener('hashchange',()=>render(true));render();
document.querySelector('footer').innerHTML=`<a class="brand footer-brand" href="#/" aria-label="BearAI home"><img src="assets/BearAI_Logo_Green.png" alt=""><span class="footer-wordmark">Bear<span class="gold">AI</span></span></a><small class="copyright">© ${new Date().getFullYear()} BearAI — Baylor University’s AI student organization. All rights reserved.</small><div class="footer-links">${link('about','About','')}${link('events','Events','')}${link('resources','Resources','')}${link('connections','Connections','')}${link('recognition','Recognition','')}${link('join','Contact & club channels','')}<a href="https://www.baylor.edu/" target="_blank" rel="noopener noreferrer">Baylor University ↗</a></div>`;
// The skip link focuses content without changing the page route.
document.querySelector('.skip').addEventListener('click',event=>{event.preventDefault();document.querySelector('#main').focus();document.querySelector('#main').scrollIntoView();});
// Close mobile navigation even when the current page is selected again.
document.querySelector('#nav').addEventListener('click',event=>{if(event.target.closest('a')){document.querySelector('#nav').classList.remove('open');document.querySelector('.menu').setAttribute('aria-expanded','false');}});


function mountExplore(){cleanupExplore();const cards=[...document.querySelectorAll('.explore-card')],media=matchMedia('(prefers-reduced-motion: reduce)');if(!cards.length||media.matches)return;const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('explore-enter');observer.unobserve(entry.target);}}),{threshold:.2});cards.forEach(card=>observer.observe(card));const stop=()=>{observer.disconnect();cards.forEach(card=>card.classList.remove('explore-enter'));media.removeEventListener('change',stop);};media.addEventListener('change',stop);cleanupExplore=stop;}



// Each card reveals once per page visit; content remains readable before entry.
function mountEntrances(){
 cleanupEntrances();
 const targets=[...document.querySelectorAll('.event-row,.closing-section')];
 const media=matchMedia('(prefers-reduced-motion: reduce)');
 if(media.matches||!('IntersectionObserver' in window))return;
 const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{
  if(entry.isIntersecting){entry.target.classList.add('content-enter');observer.unobserve(entry.target);}
 }),{threshold:0,rootMargin:'0px 0px -24px 0px'});
 targets.forEach(target=>observer.observe(target));
 const stop=()=>{observer.disconnect();targets.forEach(target=>target.classList.remove('content-enter'));media.removeEventListener('change',stop);};
 media.addEventListener('change',stop);cleanupEntrances=stop;
}
